"""Prediction utilities for the trained delivery-delay classifier."""

from collections.abc import Mapping
from pathlib import Path
import pickle

from loguru import logger
import numpy as np
import pandas as pd

from module_olist.config import MODELS_DIR, PROCESSED_DATA_DIR

MODEL_PATH = MODELS_DIR / "model.pkl"
FEATURES_PATH = PROCESSED_DATA_DIR / "test_features.csv"
PREDICTIONS_PATH = PROCESSED_DATA_DIR / "test_predictions.csv"
REQUIRED_ARTIFACT_KEYS = {"model_name", "model", "threshold", "features"}


def load_model_artifact(model_path: Path = MODEL_PATH) -> dict:
    """Load and validate an artifact produced by the training module.

    Pickle files can execute code while loading, so ``model_path`` must point to
    a trusted artifact generated by this project.
    """
    if not model_path.is_file():
        raise FileNotFoundError(
            f"Model artifact not found at {model_path}. Run the training module first."
        )

    with model_path.open("rb") as model_file:
        artifact = pickle.load(model_file)

    if not isinstance(artifact, dict):
        raise TypeError("The model artifact must be a dictionary.")

    missing_keys = REQUIRED_ARTIFACT_KEYS.difference(artifact)
    if missing_keys:
        missing = ", ".join(sorted(missing_keys))
        raise ValueError(f"Model artifact is missing required keys: {missing}")

    if not hasattr(artifact["model"], "predict_proba"):
        raise ValueError("The stored model does not provide predict_proba().")

    threshold = float(artifact["threshold"])
    if not 0.0 <= threshold <= 1.0:
        raise ValueError("The stored threshold must be between 0 and 1.")

    artifact["threshold"] = threshold
    artifact["features"] = list(artifact["features"])
    return artifact


def predict(features: pd.DataFrame, artifact: Mapping) -> pd.DataFrame:
    """Predict delay probabilities and classes using the trained threshold."""
    required_features = list(artifact["features"])
    missing_columns = set(required_features).difference(features.columns)
    if missing_columns:
        missing = ", ".join(sorted(missing_columns))
        raise ValueError(f"Inference data is missing required features: {missing}")

    probabilities = artifact["model"].predict_proba(features[required_features])[:, 1]
    threshold = float(artifact["threshold"])

    return pd.DataFrame(
        {
            "late_probability": np.asarray(probabilities, dtype=float),
            "predicted_is_late": (probabilities >= threshold).astype("int8"),
        },
        index=features.index,
    )


def predict_from_file(
    features_path: Path = FEATURES_PATH,
    model_path: Path = MODEL_PATH,
    predictions_path: Path = PREDICTIONS_PATH,
) -> pd.DataFrame:
    """Load features and model, generate predictions and save them as CSV."""
    if not features_path.is_file():
        raise FileNotFoundError(f"Inference data not found at {features_path}.")

    logger.info("Loading inference data from {}...", features_path)
    features = pd.read_csv(features_path)
    artifact = load_model_artifact(model_path)
    predictions = predict(features, artifact)

    predictions_path.parent.mkdir(parents=True, exist_ok=True)
    predictions.to_csv(predictions_path, index=False)
    logger.success(
        "Generated {:,} predictions with {} and saved them to {}",
        len(predictions),
        artifact["model_name"],
        predictions_path,
    )
    return predictions


def main() -> None:
    """Run file-based inference using the default project paths."""
    predict_from_file()


if __name__ == "__main__":
    main()
